# https://github.com/tradichel/SecurityMetricsAutomation
# IAM/stacks/VMs/cfn/UserVM.yaml
# author: @tradichel @2ndsightlab
##############################################################
Parameters:
  NameParam:
    Type: String
  AMIParam:
    Description: AMI Parameter
    Type: String
  InstanceTypeParam:
    Description: Instance type for AMI
    Type: String
  SubnetExportParam:
    Type: String
    Default: 'RemoteAccessPublicVPC-Subnet1'
  SecurityGroupIdsParam:
    Type: CommaDelimitedList
  KMSKeyIdExportParam:
    Type: String
    Default: 'DeveloperEC2KeyIDExport'

Resources:
  VM:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AMIParam
      InstanceType: !Ref InstanceTypeParam
      KeyName: !Ref NameParam
      Tags:
        -
          Key: "Name"
          Value: !Sub "${NameParam}-${InstanceTypeParam}-${AMIParam}"
      IamInstanceProfile:
          Fn::ImportValue: EC2AppDeployInstanceProfileExport
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeType: gp2
            VolumeSize: '40'
            DeleteOnTermination: 'true'
            Encrypted: 'true'
            KmsKeyId:
              Fn::ImportValue:
                !Sub "${KMSKeyIdExportParam}"
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"  
          GroupSet: !Ref SecurityGroupIdsParam
          SubnetId:
            Fn::ImportValue:
              !Sub "${SubnetExportParam}"
Outputs:
  VMOutput:
    Value: !Ref VM
    Export:
      Name: !Sub ${NameParam}-${AMIParam}


