# https://github.com/tradichel/SecurityMetricsAutomation
# OrgRoot/stacks/OrgRootUser/cfn/User.yaml
# author: @tradichel @2ndsightlab
# description: CloudFormation template to create the initial 
# Organizational Root user who deploys IAM and Governance
# permissions and creates new AWS accounts
##############################################################

Resources:

  Passwrd:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: OrgRoot-Password
      GenerateSecretString:
        SecretStringTemplate:
              !Join
                - ''
                - - '{"username": "'
                  - OrgRoot
                  - '"}'
        GenerateStringKey: password
        PasswordLength: 20

  User:
    Type: AWS::IAM::User
    Properties:
      UserName: OrgRoot
      ManagedPolicyArns: [ arn:aws:iam::aws:policy/AdministratorAccess ]
      LoginProfile:
        Password: !Sub "{{resolve:secretsmanager:${Passwrd}:SecretString:password}}"
        PasswordResetRequired: true
      
Outputs:

  UserOutput:
    Value: !Ref User
    Export:
     Name: OrgRootUserExport

  UserARNOutput:
    Value: 
      !GetAtt User.Arn
    Export:
      Name: OrgRootUserArnExport

#################################################################################
# Copyright Notice
# All Rights Reserved.
# All materials (the “Materials”) in this repository are protected by copyright 
# under U.S. Copyright laws and are the property of 2nd Sight Lab. They are provided 
# pursuant to a royalty free, perpetual license the person to whom they were presented 
# by 2nd Sight Lab and are solely for the training and education by 2nd Sight Lab.
#
# The Materials may not be copied, reproduced, distributed, offered for sale, published, 
# displayed, performed, modified, used to create derivative works, transmitted to 
# others, or used or exploited in any way, including, in whole or in part, as training 
# materials by or for any third party.
#
# The above copyright notice and this permission notice shall be included in all 
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A 
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT 
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION 
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE 
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
################################################################################
